# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/python/interface/design/maingui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 842)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                "src/main/python/interface/design\\../../../../Documents/GitHub/Kraken/src/icon.ico"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(
            "QFrame {\n"
            "    border: none;  /* Remove qualquer borda */\n"
            "    margin: 0px;   /* Define a margem como zero */\n"
            "}"
        )
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cellNameBox = QtWidgets.QComboBox(self.frame)
        self.cellNameBox.setMinimumSize(QtCore.QSize(100, 0))
        self.cellNameBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cellNameBox.setStyleSheet(
            "QComboBox {\n" "    text-align: center;\n" "}\n" ""
        )
        self.cellNameBox.setObjectName("cellNameBox")
        self.horizontalLayout.addWidget(self.cellNameBox)
        self.formulaBar = QtWidgets.QLineEdit(self.frame)
        self.formulaBar.setToolTip("")
        self.formulaBar.setText("")
        self.formulaBar.setObjectName("formulaBar")
        self.horizontalLayout.addWidget(self.formulaBar)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainSheetTable = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.mainSheetTable.sizePolicy().hasHeightForWidth()
        )
        self.mainSheetTable.setSizePolicy(sizePolicy)
        self.mainSheetTable.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.CrossCursor)
        )
        self.mainSheetTable.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.mainSheetTable.setAutoFillBackground(False)
        self.mainSheetTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainSheetTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mainSheetTable.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustIgnored
        )
        self.mainSheetTable.setRowCount(100)
        self.mainSheetTable.setColumnCount(24)
        self.mainSheetTable.setObjectName("mainSheetTable")
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainSheetTable.setHorizontalHeaderItem(23, item)
        self.mainSheetTable.horizontalHeader().setDefaultSectionSize(100)
        self.mainSheetTable.horizontalHeader().setSortIndicatorShown(False)
        self.mainSheetTable.verticalHeader().setDefaultSectionSize(22)
        self.mainSheetTable.verticalHeader().setMinimumSectionSize(22)
        self.mainSheetTable.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.mainSheetTable)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuCalcular = QtWidgets.QMenu(self.menubar)
        self.menuCalcular.setObjectName("menuCalcular")
        self.menuPressure = QtWidgets.QMenu(self.menuCalcular)
        self.menuPressure.setObjectName("menuPressure")
        self.menuTemperature_2 = QtWidgets.QMenu(self.menuCalcular)
        self.menuTemperature_2.setObjectName("menuTemperature_2")
        self.menuSobre = QtWidgets.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        MainWindow.insertToolBarBreak(self.toolBar_2)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/icons/images/new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionGerenciar_Arquivos = QtWidgets.QAction(MainWindow)
        self.actionGerenciar_Arquivos.setObjectName("actionGerenciar_Arquivos")
        self.actionCalculadora = QtWidgets.QAction(MainWindow)
        self.actionCalculadora.setObjectName("actionCalculadora")
        self.actionTOMI_index = QtWidgets.QAction(MainWindow)
        self.actionTOMI_index.setObjectName("actionTOMI_index")
        self.actionAjuda = QtWidgets.QAction(MainWindow)
        self.actionAjuda.setObjectName("actionAjuda")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.newFileToolbar = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/icons/images/new_file.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.newFileToolbar.setIcon(icon2)
        self.newFileToolbar.setObjectName("newFileToolbar")
        self.actionAbrirToolbar = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/icons/images/open_folder.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionAbrirToolbar.setIcon(icon3)
        self.actionAbrirToolbar.setObjectName("actionAbrirToolbar")
        self.actionSaveToolbar = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/icons/images/save.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionSaveToolbar.setIcon(icon4)
        self.actionSaveToolbar.setObjectName("actionSaveToolbar")
        self.actionManageFilesToolbar = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/icons/images/mng.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionManageFilesToolbar.setIcon(icon5)
        self.actionManageFilesToolbar.setObjectName("actionManageFilesToolbar")
        self.actionOpenPlotWindowToolbar = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/icons/images/simple.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionOpenPlotWindowToolbar.setIcon(icon6)
        self.actionOpenPlotWindowToolbar.setObjectName("actionOpenPlotWindowToolbar")
        self.actionChangeFontToolbar = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(":/icons/images/font.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionChangeFontToolbar.setIcon(icon7)
        self.actionChangeFontToolbar.setObjectName("actionChangeFontToolbar")
        self.actionRegressionPlotToolbar = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap(":/icons/images/complex.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionRegressionPlotToolbar.setIcon(icon8)
        self.actionRegressionPlotToolbar.setObjectName("actionRegressionPlotToolbar")
        self.actionTendencyPlot = QtWidgets.QAction(MainWindow)
        self.actionTendencyPlot.setObjectName("actionTendencyPlot")
        self.actionClassificacao_de_Fluidos = QtWidgets.QAction(MainWindow)
        self.actionClassificacao_de_Fluidos.setObjectName(
            "actionClassificacao_de_Fluidos"
        )
        self.actionImportar_Arquivo = QtWidgets.QAction(MainWindow)
        self.actionImportar_Arquivo.setEnabled(True)
        self.actionImportar_Arquivo.setObjectName("actionImportar_Arquivo")
        self.changeTextColorBtn = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(
            QtGui.QPixmap(":/icons/images/font_color.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.changeTextColorBtn.setIcon(icon9)
        self.changeTextColorBtn.setObjectName("changeTextColorBtn")
        self.changeCellColorBtn = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(
            QtGui.QPixmap(":/icons/images/fill_color.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.changeCellColorBtn.setIcon(icon10)
        self.changeCellColorBtn.setObjectName("changeCellColorBtn")
        self.alignLeftButton = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(
            QtGui.QPixmap(":/icons/images/alignLeft.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.alignLeftButton.setIcon(icon11)
        self.alignLeftButton.setObjectName("alignLeftButton")
        self.alignCenterButton = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(
            QtGui.QPixmap(":/icons/images/alignCenter.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.alignCenterButton.setIcon(icon12)
        self.alignCenterButton.setObjectName("alignCenterButton")
        self.alignRightButton = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(
            QtGui.QPixmap(":/icons/images/alignRight.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.alignRightButton.setIcon(icon13)
        self.alignRightButton.setObjectName("alignRightButton")
        self.actionFluidContact = QtWidgets.QAction(MainWindow)
        self.actionFluidContact.setObjectName("actionFluidContact")
        self.actionFluidClassification = QtWidgets.QAction(MainWindow)
        self.actionFluidClassification.setObjectName("actionFluidClassification")
        self.actionGradient_Analysis = QtWidgets.QAction(MainWindow)
        self.actionGradient_Analysis.setObjectName("actionGradient_Analysis")
        self.actionTemperatureGradient = QtWidgets.QAction(MainWindow)
        self.actionTemperatureGradient.setObjectName("actionTemperatureGradient")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionAbrir)
        self.menuFile.addAction(self.actionSalvar)
        self.menuFile.addAction(self.actionImportar_Arquivo)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSair)
        self.menuEditar.addAction(self.actionGerenciar_Arquivos)
        self.menuPressure.addAction(self.actionFluidContact)
        self.menuPressure.addAction(self.actionFluidClassification)
        self.menuTemperature_2.addAction(self.actionTemperatureGradient)
        self.menuCalcular.addAction(self.actionCalculadora)
        self.menuCalcular.addAction(self.menuPressure.menuAction())
        self.menuCalcular.addAction(self.menuTemperature_2.menuAction())
        self.menuCalcular.addAction(self.actionTOMI_index)
        self.menuSobre.addAction(self.actionAjuda)
        self.menuSobre.addAction(self.actionSobre)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuCalcular.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())
        self.toolBar.addAction(self.newFileToolbar)
        self.toolBar.addAction(self.actionAbrirToolbar)
        self.toolBar.addAction(self.actionSaveToolbar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionManageFilesToolbar)
        self.toolBar.addAction(self.actionOpenPlotWindowToolbar)
        self.toolBar.addAction(self.actionRegressionPlotToolbar)
        self.toolBar.addAction(self.actionChangeFontToolbar)
        self.toolBar.addSeparator()
        self.toolBar_2.addAction(self.changeCellColorBtn)
        self.toolBar_2.addAction(self.changeTextColorBtn)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.alignLeftButton)
        self.toolBar_2.addAction(self.alignCenterButton)
        self.toolBar_2.addAction(self.alignRightButton)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cellNameBox.setToolTip(
            _translate("MainWindow", "This area shows the current selected cell")
        )
        self.formulaBar.setPlaceholderText(_translate("MainWindow", "Type here..."))
        item = self.mainSheetTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.mainSheetTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.mainSheetTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "C"))
        item = self.mainSheetTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "D"))
        item = self.mainSheetTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "E"))
        item = self.mainSheetTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "F"))
        item = self.mainSheetTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "G"))
        item = self.mainSheetTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "I"))
        item = self.mainSheetTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "J"))
        item = self.mainSheetTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "K"))
        item = self.mainSheetTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "L"))
        item = self.mainSheetTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "M"))
        item = self.mainSheetTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "N"))
        item = self.mainSheetTable.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "O"))
        item = self.mainSheetTable.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "P"))
        item = self.mainSheetTable.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Q"))
        item = self.mainSheetTable.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "R"))
        item = self.mainSheetTable.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "S"))
        item = self.mainSheetTable.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "T"))
        item = self.mainSheetTable.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "U"))
        item = self.mainSheetTable.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "V"))
        item = self.mainSheetTable.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "W"))
        item = self.mainSheetTable.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "X"))
        item = self.mainSheetTable.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "Z"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEditar.setTitle(_translate("MainWindow", "Manage"))
        self.menuCalcular.setTitle(_translate("MainWindow", "Calculations and Plots"))
        self.menuPressure.setTitle(_translate("MainWindow", "Pressure"))
        self.menuTemperature_2.setTitle(_translate("MainWindow", "Temperature"))
        self.menuSobre.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionNew.setText(_translate("MainWindow", "New File"))
        self.actionAbrir.setText(_translate("MainWindow", "Open File"))
        self.actionSalvar.setText(_translate("MainWindow", "Save"))
        self.actionSair.setText(_translate("MainWindow", "Exit"))
        self.actionGerenciar_Arquivos.setText(_translate("MainWindow", "Manage files"))
        self.actionCalculadora.setText(_translate("MainWindow", "Simple Plot"))
        self.actionTOMI_index.setText(_translate("MainWindow", "TOMI Index"))
        self.actionAjuda.setText(_translate("MainWindow", "User guide"))
        self.actionSobre.setText(_translate("MainWindow", "About"))
        self.newFileToolbar.setText(_translate("MainWindow", "New File"))
        self.newFileToolbar.setToolTip(_translate("MainWindow", "Open a new file"))
        self.newFileToolbar.setStatusTip(
            _translate("MainWindow", "Abrir um novo arquivo .csv")
        )
        self.actionAbrirToolbar.setText(_translate("MainWindow", "Open"))
        self.actionAbrirToolbar.setToolTip(_translate("MainWindow", "Open file"))
        self.actionAbrirToolbar.setStatusTip(
            _translate("MainWindow", "Abrir um arquivo .csv já existente")
        )
        self.actionSaveToolbar.setText(_translate("MainWindow", "Save"))
        self.actionSaveToolbar.setToolTip(_translate("MainWindow", "Save file"))
        self.actionSaveToolbar.setStatusTip(
            _translate("MainWindow", "Salvar o arquivo")
        )
        self.actionManageFilesToolbar.setText(_translate("MainWindow", "Manage Files"))
        self.actionManageFilesToolbar.setToolTip(
            _translate("MainWindow", "Manage uploaded files")
        )
        self.actionManageFilesToolbar.setStatusTip(
            _translate("MainWindow", "Gerencie os arquivos que foram carregados")
        )
        self.actionOpenPlotWindowToolbar.setText(_translate("MainWindow", "Open plot"))
        self.actionOpenPlotWindowToolbar.setToolTip(
            _translate("MainWindow", "Open the plot window")
        )
        self.actionOpenPlotWindowToolbar.setStatusTip(
            _translate(
                "MainWindow",
                "Abra a seção de cálculos, para calcular gradiente de pressão e classificar poços",
            )
        )
        self.actionChangeFontToolbar.setText(_translate("MainWindow", "Fonte"))
        self.actionChangeFontToolbar.setToolTip(_translate("MainWindow", "Change font"))
        self.actionChangeFontToolbar.setStatusTip(
            _translate("MainWindow", "Altere a fonte utilizada")
        )
        self.actionRegressionPlotToolbar.setText(
            _translate("MainWindow", "Open regression plot")
        )
        self.actionRegressionPlotToolbar.setToolTip(
            _translate("MainWindow", "Open regression plot")
        )
        self.actionTendencyPlot.setText(_translate("MainWindow", "Fluid Contact Plot"))
        self.actionClassificacao_de_Fluidos.setText(
            _translate("MainWindow", "Fluid Classification")
        )
        self.actionImportar_Arquivo.setText(_translate("MainWindow", "Import data"))
        self.changeTextColorBtn.setText(_translate("MainWindow", "Change text color"))
        self.changeTextColorBtn.setToolTip(
            _translate("MainWindow", "Change text color")
        )
        self.changeCellColorBtn.setText(_translate("MainWindow", "Change cell color"))
        self.changeCellColorBtn.setToolTip(
            _translate("MainWindow", "Change cell color")
        )
        self.alignLeftButton.setText(_translate("MainWindow", "Align left"))
        self.alignLeftButton.setToolTip(_translate("MainWindow", "Align left"))
        self.alignCenterButton.setText(_translate("MainWindow", "Align center"))
        self.alignCenterButton.setToolTip(_translate("MainWindow", "Align center"))
        self.alignRightButton.setText(_translate("MainWindow", "Align right"))
        self.alignRightButton.setToolTip(_translate("MainWindow", "Align right"))
        self.actionFluidContact.setText(_translate("MainWindow", "Fluid Contact"))
        self.actionFluidClassification.setText(
            _translate("MainWindow", "Fluid Classification")
        )
        self.actionGradient_Analysis.setText(
            _translate("MainWindow", "Gradient Analysis")
        )
        self.actionTemperatureGradient.setText(
            _translate("MainWindow", "Gradient Analysis")
        )


import main_rc
