# Form implementation generated from reading ui file 'ui/about.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutWindow(object):
    def setupUi(self, AboutWindow):
        AboutWindow.setObjectName("AboutWindow")
        AboutWindow.resize(357, 296)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutWindow.sizePolicy().hasHeightForWidth())
        AboutWindow.setSizePolicy(sizePolicy)
        AboutWindow.setMinimumSize(QtCore.QSize(357, 296))
        AboutWindow.setMaximumSize(QtCore.QSize(357, 296))
        AboutWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../about.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AboutWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=AboutWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.creditsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.creditsLabel.setGeometry(QtCore.QRect(30, 90, 301, 101))
        self.creditsLabel.setObjectName("creditsLabel")
        self.giecarBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.giecarBtn.setGeometry(QtCore.QRect(60, 30, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(87)
        self.giecarBtn.setFont(font)
        self.giecarBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(171, 171, 171);\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(253, 253, 253, 255), stop:1 rgba(239, 239, 239, 255));\n"
"    font-weight: 700; /* Set font weight to 700 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:1 rgba(253, 253, 253, 255));\n"
"    border: 1px solid rgb(171, 171, 171); /* Optional: Add border color on hover */\n"
"}")
        self.giecarBtn.setObjectName("giecarBtn")
        self.githubBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.githubBtn.setGeometry(QtCore.QRect(180, 30, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(87)
        self.githubBtn.setFont(font)
        self.githubBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(171, 171, 171);\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(253, 253, 253, 255), stop:1 rgba(239, 239, 239, 255));\n"
"    font-weight: 700; /* Set font weight to 700 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:1 rgba(253, 253, 253, 255));\n"
"    border: 1px solid rgb(171, 171, 171); /* Optional: Add border color on hover */\n"
"}")
        self.githubBtn.setObjectName("githubBtn")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 190, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Pastor of Muppets")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        AboutWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AboutWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 357, 21))
        self.menubar.setObjectName("menubar")
        AboutWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AboutWindow)
        self.statusbar.setObjectName("statusbar")
        AboutWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AboutWindow)
        QtCore.QMetaObject.connectSlotsByName(AboutWindow)

    def retranslateUi(self, AboutWindow):
        _translate = QtCore.QCoreApplication.translate
        AboutWindow.setWindowTitle(_translate("AboutWindow", "MainWindow"))
        self.creditsLabel.setText(_translate("AboutWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Desenvolvido por André Albano</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">GIECAR - UFF</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">2024</span></p></body></html>"))
        self.giecarBtn.setToolTip(_translate("AboutWindow", "Acessar o site do Grupo de Interpretação Exploratória e Caracterização de Reservatório"))
        self.giecarBtn.setText(_translate("AboutWindow", "GIECAR"))
        self.githubBtn.setToolTip(_translate("AboutWindow", "Acessar o GitHub do projeto"))
        self.githubBtn.setText(_translate("AboutWindow", "GitHub"))
        self.label.setText(_translate("AboutWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">KrakeÉ</span></p></body></html>"))
